source/urls.py
from django.contrib import admin
from django.urls import path, include
from todo_list.views import IndexView
from django.conf.urls.static import static
from django.conf import settings

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', IndexView.as_view(), name='home_page'),
    path('tasks/', include('todo_list.urls')),
    path('projects/', include('projects.urls')),
    path('accounts/', include('accounts.urls')),
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

projects/models.py
from django.db import models
from django.contrib.auth.models import User
from accounts.models import UserProfile

class Project(models.Model):
    name = models.CharField(max_length=200, null=False, blank=False, verbose_name = 'Name')
    description = models.TextField(max_length=3000, null=True, blank=True, verbose_name = 'Text')
    created_at = models.DateTimeField(auto_now_add=True, verbose_name = 'Creation date and time')
    updated_at = models.DateTimeField(auto_now=True, verbose_name = 'Update date and time')
    users = models.ManyToManyField(User, related_name='projects', blank=False)

    def __str__(self):
        return self.name

todo_list/views.py
from django.shortcuts import render, redirect
from django.urls import reverse, reverse_lazy
from django.views.generic import TemplateView, ListView, DetailView, CreateView, UpdateView, DeleteView
from django.utils.http import urlencode
from .models import Task
from .forms import SearchForm, TaskForm
from django.db.models import Q
from django.core.exceptions import PermissionDenied
from django.contrib.auth.mixins import LoginRequiredMixin, PermissionRequiredMixin

class IndexView(TemplateView):
    template_name = 'index.html'

class TaskListView(ListView):
    template_name = 'todo_list/list.html'
    model = Task
    context_object_name = 'tasks'
    form = SearchForm
    paginate_by = 5
    paginate_orphans = 1
    
    def get_queryset(self):
        queryset = super().get_queryset()
        sort_by = self.request.GET.get('sort_by')
        if sort_by:
            queryset = queryset.order_by(sort_by)
        search_value = self.get_search_value()
        if search_value:
            queryset = queryset.filter(title__icontains=search_value)
        return queryset


    def get(self, request, *args, **kwargs):
        self.form = self.get_search_form()
        self.search_value = self.get_search_value()
        return super().get(request, *args, **kwargs)
    
    def get_search_form(self):
        return self.form(self.request.GET)
    
    def get_search_value(self):
        if self.form.is_valid():
            return self.form.cleaned_data.get('search')
        return None
    
    def get_context_data(self, *, object_list=None, **kwargs):
        context = super().get_context_data(object_list=object_list, **kwargs)
        context['form'] = self.form
        if self.search_value:
            context['query'] = urlencode({'search': self.search_value})
        return context

class TaskDetailView(DetailView):
    template_name = 'todo_list/detail.html'
    model = Task
    context_object_name = 'task'

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        task = self.get_object()
        context['assigned_users'] = task.users.all()
        return context

class TaskCreateView(PermissionRequiredMixin, CreateView):
    template_name = 'todo_list/create.html'
    model = Task
    form_class = TaskForm
    permission_required = ['todo_list.add_task']

    def dispatch(self, request, *args, **kwargs):
        user = request.user
        if not user.is_authenticated:
            return redirect('home_page')
        if not user.has_perm('todo_list.add_task'):
            raise PermissionDenied
        return super().dispatch(request, *args, **kwargs)

    def get_success_url(self):
        return reverse('task_detail', kwargs={'pk':self.object.pk})

class TaskUpdateView(PermissionRequiredMixin, UpdateView):
    model = Task
    template_name = 'todo_list/update.html'
    form_class = TaskForm
    context_object_name = 'task'
    permission_required = ['todo_list.change_task']

    def dispatch(self, request, *args, **kwargs):
        user = request.user
        if not user.is_authenticated:
            return redirect('home_page')
        if not user.has_perm('todo_list.change_task'):
            raise PermissionDenied
        return super().dispatch(request, *args, **kwargs)

    def get_success_url(self):
        return reverse('task_detail', kwargs={'pk': self.object.pk})
    


class TaskDeleteView(PermissionRequiredMixin, DeleteView):
    template_name = 'todo_list/delete.html'
    model = Task
    context_key = 'task'
    success_url = reverse_lazy('task_list')
    permission_required = ['todo_list.delete_task']

    def dispatch(self, request, *args, **kwargs):
        user = request.user
        if not user.is_authenticated:
            return redirect('home_page')
        if not user.has_perm('todo_list.delete_task'):
            raise PermissionDenied
        return super().dispatch(request, *args, **kwargs)

templates/partials/base.html
{% load static %}
<!DOCTYPE html>
<html lang="en">

<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>{% block title %} ToDo List | Main Page {% endblock %}</title>
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.2/dist/css/bootstrap.min.css" rel="stylesheet"
        integrity="sha384-T3c6CoIi6uLrA9TneNEoa7RxnatzjcDSCmG1MXxSR1GAsXEV/Dwwykc2MPK8M2HN" crossorigin="anonymous">
    <link rel="stylesheet" href="{% static 'css/styles.css' %}">
    {% block css %}{% endblock %}
</head>

<body>
    {% include 'partials/navigation.html' %}

    <div class="container pt-3">
        {% block user_menu %}
        {% endblock %}

        {% block content %}
        {% endblock %}
    </div>

    {% block js %}
        <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.3.2/dist/js/bootstrap.bundle.min.js"
            integrity="sha384-C6RzsynM9kWDrMNeT87bh95OGNyZPhcTNXj1NW7RuBCsyN/o0jlpcV8Qyq46cDfL"
            crossorigin="anonymous">
        </script>
    {% endblock %}
</body>

</html>

templates/partials/create_update_form.html
{% csrf_token %}

<div class="w-50">
    {% for error in form.non_field_errors %}
        <p class="alert alert-danger">{{ error }}</p>
    {% endfor %}

    {% for field in form %}
        <div class="mb-3">
            <label class="form_label" for="{{ field.id_for_label }}">{{ field.label }}</label>
            {{ field }}
            {% for error in field.errors %}
                <p class="text-danger">{{ error }}</p>
            {% endfor %}
        </div>
    {% endfor %}
</div>

<button type="submit" class="btn btn-primary mt-3">{{button_text}}</button>

templates/partials/navigation.html
<nav class="navbar navbar-expand-lg bg-body-tertiary">
  <div class="container">
      <a class="navbar-brand" href="{% url 'home_page' %}">
          <img src="https://static.vecteezy.com/system/resources/previews/003/529/153/large_2x/business-to-do-list-flat-icon-modern-style-vector.jpg" alt="" height="40">
          MyBLOG
      </a>
      <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarNav"
          aria-controls="navbarNav" aria-expanded="false" aria-label="Toggle navigation">
          <span class="navbar-toggler-icon"></span>
      </button>
      <div class="collapse navbar-collapse justify-content-between" id="navbarNav">
          <div class="navbar-nav">
              <a class="nav-link active" aria-current="page" href="{% url 'home_page' %}">Home</a>
              <a class="nav-link active" aria-current="page" href="{% url 'project_list' %}">Project list</a>
              <a class="nav-link active" aria-current="page" href="{% url 'project_create' %}">Add project</a>
              <a class="nav-link active" aria-current="page" href="{% url 'task_list' %}">Task list</a>
              <a class="nav-link active" aria-current="page" href="{% url 'task_create' %}">Add task</a>
          </div>
          <div class="d-flex">
            {% if not request.user.is_authenticated %}
            <a class="btn btn-outline-success btn-sm me-3" aria-current="page" href="{% url 'login' %}?next={{ request.get_full_path }}">Login</a>
            <a class="btn btn-outline-secondary btn-sm" aria-current="page" href="{% url 'register' %}?next={{ request.get_full_path }}">Register</a>
            {% else %}
                <div class="d-flex align-items-center me-3">
                    Hello, <a href="{% url 'user_detail' user.pk %}">{{ user.username }}</a>!
                </div>
                <a class="btn btn-outline-danger btn-sm" aria-current="page" href="{% url 'logout' %}?next={{ request.get_full_path }}">Logout</a>
            {% endif %}
          </div>
      </div>
  </div>
</nav>

templates/partials/pagination.html
<nav aria-label="Page navigation">
    <ul class="pagination">
        <!-- First page -->
        <li class="page-item">
            <a href="?page=1" class="page-link">First</a>
        </li>

        <!-- Previous page -->
        {% if page_obj.has_previous %}
        <li class="page-item">
            <a href="?page={{ page_obj.previous_page_number }}" class="page-link">Previous</a>
        </li>
        {% else %}
        <li class="page-item disabled">
            <span class="page-link">Previous</span>
        </li>
        {% endif %}

        <!-- List of pages -->
        {% for page in page_obj.paginator.page_range %}
            <li class="page-item">
                <a class="page-link" href="?page={{ page }}">{{ page }}</a>
            </li>
        {% endfor %}

        <!-- Next page -->
        {% if page_obj.has_next %}
        <li class="page-item">
            <a href="?page={{ page_obj.next_page_number }}" class="page-link">Next</a>
        </li>
        {% else %}
        <li class="page-item disabled">
            <span class="page-link">Next</span>
        </li>
        {% endif %}

        <!-- Last page -->
        <li class="page-item">
            <a class="page-link" href="?page={{ page_obj.paginator.num_pages }}" aria-label="Last">
                Last
            </a>
        </li>
    </ul>
</nav>

templates/partials/project_list.html
{% if is_paginated %}
    {% include 'partials/pagination.html' %}
{% endif %}

{% for task in tasks %}
    <div class="box">
        <h3><a href="{% url 'project_detail' project.pk %}">{{ post.title }}</a></h3>

        <div>
            <a href="{% url 'user_detail' project.user_id %}">{{ post.author }}</a>
            | {{ project.created_at|date:"d.m.Y H:i:s" }}
        </div>
        <div>Updated at: {{ project.updated_at|date:"d.m.Y H:i:s" }}</div>
        
        {% if perms.projects.change_project or project.user == request.user %}
            <div><a href="{% url 'project_update' project.pk %}">Update</a></div>
        {% endif %}
        {% if perms.projects.delete_project or project.user == request.user %}
            <div><a href="{% url 'project_delete' project.pk %}">Delete</a></div>
        {% endif %}
    </div>
{% empty %}
    <h2 class="text-center">No projects</h2>
{% endfor %}

{% if is_paginated %}
    {% include 'partials/pagination.html' %}
{% endif %}

templates/partials/search.html
<form class="d-flex" method="GET">
    <input type="search" name="search" class="form-control">
    <button class="btn btn-success">Search</button>

    {% for error in form.search.errors %}
        <p class="form-error">{{ error }}</p>
    {% endfor %}
</form>

templates/partials/user_forms.html
{% if not fields_only %}
    <form action="{{ action_url }}" method="{{ form_method }}" enctype="multipart/form-data" class="w-50">
        {% csrf_token %}
{% endif %}


        {% for error in form.non_field_errors %}
            <p class="text-danger">{{ error }}</p>
        {% endfor %}

        {% for field in form %}
            <div class="input-group mb-3">
                <span class="input-group-text">{{ field.label }}</span>
                {{ field }}

                {% for error in field.errors %}
                    <p class="text-danger">{{ error }}</p>
                {% endfor %}
            </div>
        {% endfor %}


{% if not fields_only %}
        <button type="submit" class="btn btn-primary">{{ button_text|default:"Submit" }}</button>
    </form>
{% endif %}